USE [CabTransport]
GO

/****** Object:  Table [dbo].[DC]    Script Date: 3/30/2015 12:56:55 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DC]') AND TYPE IN (N'U'))
CREATE TABLE [dbo].[DC](
	[DCID] [int] IDENTITY(1,1) NOT NULL,
	[DCName] [char](20) NULL,
	[IsActive] [bit] NULL,
	[CreatedDate] [datetime] NULL,
	[CreatedBy] [char](20) NULL,
	[ModifiedDate] [datetime] NULL,
	[ModifiedBy] [char](20) NULL,
 CONSTRAINT [PK__DC__25D0BD91561B6B51] PRIMARY KEY CLUSTERED 
(
	[DCID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[DC] ADD  CONSTRAINT [DF_DC_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO